<?xml version="1.0"?>
<package format="3">
  <name>tunnel_anomaly_detection</name>
  <version>0.1.0</version>
  <description>Baseline point-cloud comparison and RViz anomaly visualization for tunnel inspection.</description>
  <maintainer email="mohamad@example.com">Mohamad Alquraan</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>pcl_conversions</depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
